// GENERATED by scripts/generate-tenant-models.cjs from prisma/schema.prisma. Do not edit.

export const ALL_MODEL_NAMES: readonly string[] = [];

export const TENANT_MODEL_NAMES: readonly string[] = [];
