-- Reverses 0002_core. Drops everything the migration created; data in these tables is lost.
DROP TRIGGER IF EXISTS audit_events_append_only ON "audit_events";
DROP FUNCTION IF EXISTS audit_events_reject_change();
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "notes" CASCADE;
DROP TABLE IF EXISTS "tasks" CASCADE;
DROP TABLE IF EXISTS "inventory_locations" CASCADE;
DROP TABLE IF EXISTS "tax_classes" CASCADE;
DROP TABLE IF EXISTS "units" CASCADE;
DROP TABLE IF EXISTS "approval_requests" CASCADE;
DROP TABLE IF EXISTS "status_history" CASCADE;
DROP TABLE IF EXISTS "workflow_transitions" CASCADE;
DROP TABLE IF EXISTS "workflow_states" CASCADE;
DROP TABLE IF EXISTS "workflows" CASCADE;
DROP TABLE IF EXISTS "field_definitions" CASCADE;
DROP TABLE IF EXISTS "file_assets" CASCADE;
DROP TABLE IF EXISTS "document_sequences" CASCADE;
DROP TABLE IF EXISTS "idempotency_keys" CASCADE;
DROP TABLE IF EXISTS "audit_events" CASCADE;
DROP TABLE IF EXISTS "invitations" CASCADE;
DROP TABLE IF EXISTS "user_workspace_roles" CASCADE;
DROP TABLE IF EXISTS "roles" CASCADE;
DROP TABLE IF EXISTS "user_workspaces" CASCADE;
DROP TABLE IF EXISTS "platform_settings" CASCADE;
DROP TABLE IF EXISTS "industry_profiles" CASCADE;
DROP TABLE IF EXISTS "login_attempts" CASCADE;
DROP TABLE IF EXISTS "password_reset_tokens" CASCADE;
DROP TABLE IF EXISTS "user_sessions" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "workspaces" CASCADE;
DROP TYPE IF EXISTS "workspace_status";
DROP TYPE IF EXISTS "user_status";
DROP TYPE IF EXISTS "document_type";
DROP TYPE IF EXISTS "field_entity";
DROP TYPE IF EXISTS "field_type";
DROP TYPE IF EXISTS "workflow_entity";
DROP TYPE IF EXISTS "state_category";
DROP TYPE IF EXISTS "approval_status";
DROP TYPE IF EXISTS "task_type";
DROP TYPE IF EXISTS "task_status";
