/** One demo product. Dimensions are centimetres; prices are rupees as decimal strings. */
export interface DemoProduct {
  code: string;
  name: string;
  /** A sub-category of the furniture profile. */
  category: string;
  price: string;
  cost: string;
  material: 'wood' | 'leather' | 'fabric' | 'metal' | 'glass' | 'marble' | 'mdf';
  finish: 'matte' | 'gloss' | 'natural' | 'polished' | 'lacquer' | 'upholstered';
  color: string;
  size: [width: number, depth: number, height: number];
  aliases: string[];
  tags?: string[];
  madeToOrder?: boolean;
  /** Variant colours (the `color` variant-axis field); none means a single default variant. */
  variantColors?: Array<'brown' | 'black' | 'grey' | 'beige' | 'white' | 'blue' | 'green'>;
  minStock?: string;
}

export const DEMO_PRODUCTS: readonly DemoProduct[] = [
  {
    code: 'SOF-001',
    name: 'Milano Corner Sofa',
    category: 'Sectional sofas',
    price: '145000.00',
    cost: '92000.00',
    material: 'fabric',
    finish: 'upholstered',
    color: 'Grey',
    size: [280, 180, 85],
    aliases: ['L shape sofa', 'corner couch', 'کارنر صوفہ'],
    variantColors: ['grey', 'beige', 'blue'],
    minStock: '1',
  },
  {
    code: 'SOF-002',
    name: 'Oslo 3-Seater Sofa',
    category: 'Sofa sets',
    price: '78000.00',
    cost: '49000.00',
    material: 'fabric',
    finish: 'upholstered',
    color: 'Beige',
    size: [210, 90, 80],
    aliases: ['three seater', 'couch', 'settee'],
    variantColors: ['beige', 'grey'],
    minStock: '2',
  },
  {
    code: 'SOF-003',
    name: 'Royal Leather Sofa Set 7-Seater',
    category: 'Sofa sets',
    price: '215000.00',
    cost: '140000.00',
    material: 'leather',
    finish: 'polished',
    color: 'Brown',
    size: [320, 95, 90],
    aliases: ['seven seater', 'sofa set', 'leather couch'],
    tags: ['bestseller'],
    madeToOrder: true,
  },
  {
    code: 'SOF-004',
    name: 'Cosmo Recliner',
    category: 'Recliners',
    price: '62000.00',
    cost: '40000.00',
    material: 'leather',
    finish: 'matte',
    color: 'Black',
    size: [90, 95, 105],
    aliases: ['reclining chair', 'lazy chair'],
    variantColors: ['black', 'brown'],
    minStock: '2',
  },
  {
    code: 'SOF-005',
    name: 'Nordic Loveseat',
    category: 'Sofa sets',
    price: '54000.00',
    cost: '34000.00',
    material: 'fabric',
    finish: 'upholstered',
    color: 'Green',
    size: [150, 85, 80],
    aliases: ['two seater', 'small sofa'],
    variantColors: ['green', 'grey', 'blue'],
  },
  {
    code: 'BED-001',
    name: 'Heritage King Bed',
    category: 'Double beds',
    price: '165000.00',
    cost: '105000.00',
    material: 'wood',
    finish: 'polished',
    color: 'Walnut',
    size: [200, 215, 120],
    aliases: ['king size bed', 'double bed', 'شاہی بیڈ'],
    tags: ['bestseller'],
    madeToOrder: true,
  },
  {
    code: 'BED-002',
    name: 'Luna Queen Bed with Storage',
    category: 'Double beds',
    price: '98000.00',
    cost: '62000.00',
    material: 'mdf',
    finish: 'matte',
    color: 'White',
    size: [165, 215, 110],
    aliases: ['queen bed', 'storage bed'],
    variantColors: ['white', 'grey'],
    minStock: '1',
  },
  {
    code: 'BED-003',
    name: 'Kids Bunk Bed',
    category: 'Single beds',
    price: '58000.00',
    cost: '36000.00',
    material: 'wood',
    finish: 'lacquer',
    color: 'Natural',
    size: [100, 200, 160],
    aliases: ['bunk bed', 'children bed'],
  },
  {
    code: 'BED-004',
    name: 'Zen Single Bed',
    category: 'Single beds',
    price: '32000.00',
    cost: '20000.00',
    material: 'wood',
    finish: 'natural',
    color: 'Oak',
    size: [100, 200, 90],
    aliases: ['single bed', 'twin bed'],
    minStock: '3',
  },
  {
    code: 'BED-005',
    name: 'ComfortPlus Orthopedic Mattress Queen',
    category: 'Mattresses',
    price: '45000.00',
    cost: '28000.00',
    material: 'fabric',
    finish: 'upholstered',
    color: 'White',
    size: [152, 200, 25],
    aliases: ['mattress', 'spring mattress', 'گدا'],
    minStock: '4',
  },
  {
    code: 'TAB-001',
    name: 'Granite Dining Table 6-Seater',
    category: 'Dining tables',
    price: '120000.00',
    cost: '76000.00',
    material: 'marble',
    finish: 'polished',
    color: 'Black',
    size: [180, 90, 76],
    aliases: ['dining table', 'marble table', 'کھانے کی میز'],
    tags: ['bestseller'],
  },
  {
    code: 'TAB-002',
    name: 'Teak Dining Table 8-Seater',
    category: 'Dining tables',
    price: '175000.00',
    cost: '112000.00',
    material: 'wood',
    finish: 'natural',
    color: 'Teak',
    size: [240, 100, 76],
    aliases: ['eight seater table', 'wooden dining table'],
    madeToOrder: true,
  },
  {
    code: 'TAB-003',
    name: 'Glass Top Coffee Table',
    category: 'Coffee tables',
    price: '28000.00',
    cost: '17000.00',
    material: 'glass',
    finish: 'gloss',
    color: 'Clear',
    size: [110, 60, 42],
    aliases: ['centre table', 'tea table'],
    variantColors: ['black', 'white'],
  },
  {
    code: 'TAB-004',
    name: 'Round Marble Coffee Table',
    category: 'Coffee tables',
    price: '36000.00',
    cost: '22000.00',
    material: 'marble',
    finish: 'polished',
    color: 'White',
    size: [80, 80, 45],
    aliases: ['round table', 'centre table'],
  },
  {
    code: 'TAB-005',
    name: 'Walnut Side Table',
    category: 'Side tables',
    price: '14500.00',
    cost: '8500.00',
    material: 'wood',
    finish: 'matte',
    color: 'Walnut',
    size: [45, 45, 55],
    aliases: ['end table', 'lamp table', 'bedside table'],
    minStock: '4',
  },
  {
    code: 'CHR-001',
    name: 'Classic Dining Chair',
    category: 'Dining chairs',
    price: '12500.00',
    cost: '7200.00',
    material: 'wood',
    finish: 'lacquer',
    color: 'Brown',
    size: [45, 50, 95],
    aliases: ['dining chair', 'کرسی'],
    variantColors: ['brown', 'black', 'white'],
    minStock: '6',
  },
  {
    code: 'CHR-002',
    name: 'Velvet Dining Chair',
    category: 'Dining chairs',
    price: '16500.00',
    cost: '9800.00',
    material: 'fabric',
    finish: 'upholstered',
    color: 'Green',
    size: [48, 55, 90],
    aliases: ['velvet chair', 'upholstered chair'],
    variantColors: ['green', 'blue', 'grey'],
    minStock: '6',
  },
  {
    code: 'CHR-003',
    name: 'ErgoMax Office Chair',
    category: 'Office chairs',
    price: '38000.00',
    cost: '23000.00',
    material: 'fabric',
    finish: 'matte',
    color: 'Black',
    size: [65, 65, 120],
    aliases: ['executive chair', 'revolving chair', 'computer chair'],
    variantColors: ['black', 'grey'],
    minStock: '3',
  },
  {
    code: 'CHR-004',
    name: 'Mesh Task Chair',
    category: 'Office chairs',
    price: '19500.00',
    cost: '11500.00',
    material: 'metal',
    finish: 'matte',
    color: 'Grey',
    size: [60, 60, 105],
    aliases: ['staff chair', 'mesh chair'],
    minStock: '5',
  },
  {
    code: 'CHR-005',
    name: 'Wingback Accent Chair',
    category: 'Accent chairs',
    price: '34000.00',
    cost: '21000.00',
    material: 'fabric',
    finish: 'upholstered',
    color: 'Blue',
    size: [75, 80, 105],
    aliases: ['armchair', 'wing chair'],
    variantColors: ['blue', 'beige'],
  },
  {
    code: 'STO-001',
    name: 'Sliding Door Wardrobe 3-Door',
    category: 'Wardrobes',
    price: '135000.00',
    cost: '86000.00',
    material: 'mdf',
    finish: 'gloss',
    color: 'White',
    size: [180, 60, 220],
    aliases: ['almari', 'cupboard', 'الماری'],
    tags: ['bestseller'],
    madeToOrder: true,
  },
  {
    code: 'STO-002',
    name: 'Classic 2-Door Wardrobe',
    category: 'Wardrobes',
    price: '88000.00',
    cost: '55000.00',
    material: 'wood',
    finish: 'polished',
    color: 'Walnut',
    size: [120, 55, 210],
    aliases: ['two door almari', 'closet'],
  },
  {
    code: 'STO-003',
    name: 'Floating Wall Shelf Set',
    category: 'Shelves',
    price: '9500.00',
    cost: '5200.00',
    material: 'wood',
    finish: 'matte',
    color: 'Oak',
    size: [90, 20, 4],
    aliases: ['wall shelf', 'floating shelf'],
    variantColors: ['brown', 'white', 'black'],
    minStock: '8',
  },
  {
    code: 'STO-004',
    name: 'Industrial Bookcase 5-Tier',
    category: 'Shelves',
    price: '42000.00',
    cost: '26000.00',
    material: 'metal',
    finish: 'matte',
    color: 'Black',
    size: [80, 32, 180],
    aliases: ['book shelf', 'display rack'],
  },
  {
    code: 'STO-005',
    name: 'TV Cabinet 180cm',
    category: 'Cabinets',
    price: '52000.00',
    cost: '32000.00',
    material: 'mdf',
    finish: 'matte',
    color: 'Grey',
    size: [180, 40, 50],
    aliases: ['tv unit', 'tv console', 'tv trolley'],
    variantColors: ['grey', 'white'],
  },
  {
    code: 'STO-006',
    name: 'Shoe Cabinet 4-Door',
    category: 'Cabinets',
    price: '26000.00',
    cost: '15500.00',
    material: 'mdf',
    finish: 'matte',
    color: 'White',
    size: [80, 30, 120],
    aliases: ['shoe rack', 'shoe storage'],
    minStock: '2',
  },
  {
    code: 'OFF-001',
    name: 'Executive Desk 180cm',
    category: 'Desks',
    price: '98000.00',
    cost: '61000.00',
    material: 'wood',
    finish: 'polished',
    color: 'Walnut',
    size: [180, 90, 76],
    aliases: ['boss table', 'office desk', 'manager table'],
    madeToOrder: true,
  },
  {
    code: 'OFF-002',
    name: 'Standing Desk Electric',
    category: 'Desks',
    price: '72000.00',
    cost: '46000.00',
    material: 'metal',
    finish: 'matte',
    color: 'Black',
    size: [140, 70, 120],
    aliases: ['height adjustable desk', 'sit stand desk'],
    variantColors: ['black', 'white'],
    minStock: '2',
  },
  {
    code: 'OFF-003',
    name: 'Workstation Desk with Drawers',
    category: 'Desks',
    price: '46000.00',
    cost: '28000.00',
    material: 'mdf',
    finish: 'matte',
    color: 'Oak',
    size: [140, 60, 75],
    aliases: ['computer table', 'study table'],
  },
  {
    code: 'OFF-004',
    name: 'Steel Filing Cabinet 4-Drawer',
    category: 'Filing cabinets',
    price: '31000.00',
    cost: '19000.00',
    material: 'metal',
    finish: 'matte',
    color: 'Grey',
    size: [47, 62, 132],
    aliases: ['file cabinet', 'document storage'],
    minStock: '3',
  },
];
