/** Demo people: synthetic names and numbers, none of them real. */
export interface DemoCustomer {
  fullName: string;
  phones: string[];
  email: string | null;
  city: string;
  tags: string[];
  source: string;
  /** Email of the demo staff member the customer is assigned to, if any. */
  assignedTo: 'salesperson@demo.test' | 'manager@demo.test' | 'cashier@demo.test' | null;
  channel: 'WHATSAPP' | 'PHONE' | 'EMAIL' | 'INSTAGRAM' | 'FACEBOOK';
}

export const DEMO_CUSTOMERS: readonly DemoCustomer[] = [
  {
    fullName: 'Ayesha Siddiqui',
    phones: ['0300-5100001'],
    email: 'ayesha.siddiqui@demo.test',
    city: 'Karachi',
    tags: ['vip'],
    source: 'Instagram',
    assignedTo: 'salesperson@demo.test',
    channel: 'WHATSAPP',
  },
  {
    fullName: 'Bilal Ahmed',
    phones: ['0301-5100002', '0321-5100102'],
    email: 'bilal.ahmed@demo.test',
    city: 'Lahore',
    tags: ['repeat'],
    source: 'Walk-in',
    assignedTo: 'salesperson@demo.test',
    channel: 'PHONE',
  },
  {
    fullName: 'Fatima Zahra',
    phones: ['0302-5100003'],
    email: null,
    city: 'Islamabad',
    tags: [],
    source: 'Facebook',
    assignedTo: 'manager@demo.test',
    channel: 'FACEBOOK',
  },
  {
    fullName: 'Hamza Qureshi',
    phones: ['0303-5100004'],
    email: 'hamza.q@demo.test',
    city: 'Karachi',
    tags: ['contractor'],
    source: 'Referral',
    assignedTo: 'manager@demo.test',
    channel: 'EMAIL',
  },
  {
    fullName: 'Iqra Nawaz',
    phones: ['0304-5100005'],
    email: 'iqra.nawaz@demo.test',
    city: 'Lahore',
    tags: ['vip', 'repeat'],
    source: 'Instagram',
    assignedTo: 'salesperson@demo.test',
    channel: 'INSTAGRAM',
  },
  {
    fullName: 'Junaid Iqbal',
    phones: ['0305-5100006'],
    email: null,
    city: 'Faisalabad',
    tags: [],
    source: 'Walk-in',
    assignedTo: null,
    channel: 'PHONE',
  },
  {
    fullName: 'Khadija Rehman',
    phones: ['0306-5100007'],
    email: 'khadija.r@demo.test',
    city: 'Karachi',
    tags: ['designer'],
    source: 'Referral',
    assignedTo: 'salesperson@demo.test',
    channel: 'WHATSAPP',
  },
  {
    fullName: 'Lubna Farooq',
    phones: ['0307-5100008'],
    email: null,
    city: 'Multan',
    tags: [],
    source: 'Website',
    assignedTo: 'cashier@demo.test',
    channel: 'WHATSAPP',
  },
  {
    fullName: 'Mustafa Raza',
    phones: ['0308-5100009'],
    email: 'mustafa.raza@demo.test',
    city: 'Lahore',
    tags: ['contractor', 'repeat'],
    source: 'Referral',
    assignedTo: 'manager@demo.test',
    channel: 'EMAIL',
  },
  {
    fullName: 'Nadia Hussain',
    phones: ['0309-5100010'],
    email: 'nadia.h@demo.test',
    city: 'Islamabad',
    tags: ['vip'],
    source: 'Instagram',
    assignedTo: 'salesperson@demo.test',
    channel: 'INSTAGRAM',
  },
  {
    fullName: 'Omar Sheikh',
    phones: ['0310-5100011'],
    email: null,
    city: 'Karachi',
    tags: [],
    source: 'Walk-in',
    assignedTo: null,
    channel: 'PHONE',
  },
  {
    fullName: 'Parveen Akhtar',
    phones: ['0311-5100012'],
    email: 'parveen.akhtar@demo.test',
    city: 'Peshawar',
    tags: [],
    source: 'Facebook',
    assignedTo: 'salesperson@demo.test',
    channel: 'FACEBOOK',
  },
  {
    fullName: 'Qasim Mahmood',
    phones: ['0312-5100013'],
    email: null,
    city: 'Lahore',
    tags: ['repeat'],
    source: 'Walk-in',
    assignedTo: 'cashier@demo.test',
    channel: 'PHONE',
  },
  {
    fullName: 'Rabia Anwar',
    phones: ['0313-5100014'],
    email: 'rabia.anwar@demo.test',
    city: 'Karachi',
    tags: ['designer', 'vip'],
    source: 'Referral',
    assignedTo: 'manager@demo.test',
    channel: 'EMAIL',
  },
  {
    fullName: 'Saad Butt',
    phones: ['0314-5100015'],
    email: null,
    city: 'Gujranwala',
    tags: [],
    source: 'Website',
    assignedTo: null,
    channel: 'WHATSAPP',
  },
  {
    fullName: 'Tahira Yousuf',
    phones: ['0315-5100016'],
    email: 'tahira.y@demo.test',
    city: 'Islamabad',
    tags: [],
    source: 'Instagram',
    assignedTo: 'salesperson@demo.test',
    channel: 'INSTAGRAM',
  },
  {
    fullName: 'Usman Ghani',
    phones: ['0316-5100017', '021-5100117'],
    email: 'usman.ghani@demo.test',
    city: 'Karachi',
    tags: ['contractor'],
    source: 'Referral',
    assignedTo: 'manager@demo.test',
    channel: 'PHONE',
  },
  {
    fullName: 'Vania Chaudhry',
    phones: ['0317-5100018'],
    email: 'vania.c@demo.test',
    city: 'Lahore',
    tags: ['vip'],
    source: 'Instagram',
    assignedTo: 'salesperson@demo.test',
    channel: 'WHATSAPP',
  },
  {
    fullName: 'Waqar Younas',
    phones: ['0318-5100019'],
    email: null,
    city: 'Sialkot',
    tags: [],
    source: 'Walk-in',
    assignedTo: null,
    channel: 'PHONE',
  },
  {
    fullName: 'Zoya Malik',
    phones: ['0319-5100020'],
    email: 'zoya.malik@demo.test',
    city: 'Karachi',
    tags: ['repeat'],
    source: 'Facebook',
    assignedTo: 'cashier@demo.test',
    channel: 'FACEBOOK',
  },
];

export type DemoStage =
  'new' | 'contacted' | 'qualified' | 'quoted' | 'negotiation' | 'won' | 'lost';

export interface DemoLead {
  fullName: string;
  phone: string;
  email?: string;
  interest: string;
  /** Product code from the demo catalog the lead is interested in. */
  productCode?: string;
  requirements: string;
  quantity: string;
  estimatedValue: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH';
  source: 'MESSAGING' | 'SOCIAL' | 'STORE' | 'WEBSITE' | 'MANUAL';
  channel?: string;
  campaign?: string;
  stage: DemoStage;
  lostReason?: string;
  assignedTo: 'salesperson@demo.test' | 'manager@demo.test' | null;
  /** Days from now for the next action (negative = overdue). */
  followUpInDays?: number;
  nextAction?: string;
  customFields: Record<string, unknown>;
  /** The lead is linked to (or converted into) a customer. */
  convert?: boolean;
}

const cm = (value: number) => ({ value: String(value), unit: 'cm' });

export const DEMO_LEADS: readonly DemoLead[] = [
  {
    fullName: 'Sana Tariq',
    phone: '0320-6100001',
    interest: 'L-shaped sofa for the lounge',
    productCode: 'SOF-001',
    requirements: 'Grey, stain-resistant fabric, fits a 3 m wall',
    quantity: '1',
    estimatedValue: '150000.00',
    priority: 'HIGH',
    source: 'SOCIAL',
    channel: 'INSTAGRAM',
    campaign: 'Eid collection',
    stage: 'new',
    assignedTo: 'salesperson@demo.test',
    followUpInDays: 1,
    nextAction: 'Call to confirm room measurements',
    customFields: {
      size_type: 'custom',
      length: { value: '9', unit: 'ft' },
      width: { value: '6', unit: 'ft' },
      material: 'fabric',
      color: 'Grey',
    },
  },
  {
    fullName: 'Adeel Rauf',
    phone: '0321-6100002',
    interest: 'Dining table for eight',
    productCode: 'TAB-002',
    requirements: 'Teak, seats eight, round corners',
    quantity: '1',
    estimatedValue: '175000.00',
    priority: 'MEDIUM',
    source: 'WEBSITE',
    stage: 'new',
    assignedTo: null,
    customFields: { size_type: 'standard', material: 'wood', wood_type: 'teak' },
  },
  {
    fullName: 'Mehreen Gul',
    phone: '0322-6100003',
    interest: 'Bedroom set',
    productCode: 'BED-001',
    requirements: 'King bed with two side tables, walnut',
    quantity: '1',
    estimatedValue: '260000.00',
    priority: 'HIGH',
    source: 'MESSAGING',
    channel: 'WHATSAPP',
    stage: 'contacted',
    assignedTo: 'salesperson@demo.test',
    followUpInDays: 0,
    nextAction: 'Send catalogue and prices',
    customFields: { size_type: 'standard', material: 'wood', wood_type: 'walnut' },
  },
  {
    fullName: 'Farhan Saeed',
    phone: '0323-6100004',
    interest: 'Office desks for a small team',
    productCode: 'OFF-001',
    requirements: 'Four desks with drawers, matching chairs',
    quantity: '4',
    estimatedValue: '420000.00',
    priority: 'MEDIUM',
    source: 'STORE',
    stage: 'contacted',
    assignedTo: 'manager@demo.test',
    followUpInDays: 2,
    nextAction: 'Visit the office to measure',
    customFields: {
      size_type: 'custom',
      length: cm(150),
      width: cm(70),
      height: cm(75),
      material: 'mdf',
    },
  },
  {
    fullName: 'Hina Kamal',
    phone: '0324-6100005',
    interest: 'Wardrobe 3 door',
    productCode: 'STO-001',
    requirements: 'White gloss, sliding doors, floor to ceiling',
    quantity: '1',
    estimatedValue: '135000.00',
    priority: 'MEDIUM',
    source: 'SOCIAL',
    channel: 'FACEBOOK',
    stage: 'qualified',
    assignedTo: 'salesperson@demo.test',
    followUpInDays: -1,
    nextAction: 'Chase for a decision',
    customFields: {
      size_type: 'custom',
      height: cm(240),
      width: cm(200),
      material: 'mdf',
      color: 'White',
    },
  },
  {
    fullName: 'Imran Dar',
    phone: '0325-6100006',
    interest: 'Leather sofa set',
    productCode: 'SOF-003',
    requirements: 'Seven-seater, brown leather',
    quantity: '1',
    estimatedValue: '215000.00',
    priority: 'HIGH',
    source: 'STORE',
    stage: 'qualified',
    assignedTo: 'manager@demo.test',
    followUpInDays: 3,
    nextAction: 'Arrange a showroom visit',
    customFields: { size_type: 'standard', material: 'leather', color: 'Brown' },
  },
  {
    fullName: 'Jawad Pervaiz',
    phone: '0326-6100007',
    interest: 'Recliners for a cinema room',
    productCode: 'SOF-004',
    requirements: 'Four recliners in black',
    quantity: '4',
    estimatedValue: '248000.00',
    priority: 'MEDIUM',
    source: 'WEBSITE',
    stage: 'quoted',
    assignedTo: 'salesperson@demo.test',
    followUpInDays: 2,
    nextAction: 'Follow up on the quotation',
    customFields: { size_type: 'standard', material: 'leather', color: 'Black' },
  },
  {
    fullName: 'Kiran Javed',
    phone: '0327-6100008',
    interest: 'Dining chairs x6',
    productCode: 'CHR-002',
    requirements: 'Velvet, green, with arms',
    quantity: '6',
    estimatedValue: '99000.00',
    priority: 'LOW',
    source: 'MESSAGING',
    channel: 'WHATSAPP',
    stage: 'quoted',
    assignedTo: 'salesperson@demo.test',
    customFields: { size_type: 'standard', material: 'fabric', color: 'Green' },
  },
  {
    fullName: 'Laiba Noor',
    phone: '0328-6100009',
    interest: 'Home office desk',
    productCode: 'OFF-002',
    requirements: 'Standing desk, black, cable tray',
    quantity: '1',
    estimatedValue: '72000.00',
    priority: 'MEDIUM',
    source: 'SOCIAL',
    channel: 'INSTAGRAM',
    stage: 'negotiation',
    assignedTo: 'manager@demo.test',
    followUpInDays: 1,
    nextAction: 'Agree on the final price',
    customFields: { size_type: 'standard', material: 'metal', color: 'Black' },
  },
  {
    fullName: 'Moiz Abbas',
    phone: '0329-6100010',
    interest: 'Full living room',
    productCode: 'SOF-002',
    requirements: 'Sofa, coffee table and TV cabinet in matching grey',
    quantity: '1',
    estimatedValue: '280000.00',
    priority: 'HIGH',
    source: 'STORE',
    stage: 'negotiation',
    assignedTo: 'salesperson@demo.test',
    followUpInDays: 0,
    nextAction: 'Send the revised offer',
    customFields: {
      size_type: 'custom',
      length: { value: '8', unit: 'ft' },
      material: 'fabric',
      color: 'Grey',
    },
  },
  {
    fullName: 'Nimra Shafiq',
    phone: '0330-6100011',
    interest: 'Single bed for a child',
    productCode: 'BED-004',
    requirements: 'Oak, with storage drawers',
    quantity: '1',
    estimatedValue: '32000.00',
    priority: 'LOW',
    source: 'STORE',
    stage: 'won',
    assignedTo: 'salesperson@demo.test',
    convert: true,
    customFields: { size_type: 'standard', material: 'wood', wood_type: 'oak' },
  },
  {
    fullName: 'Osama Latif',
    phone: '0331-6100012',
    interest: 'Bookcase',
    productCode: 'STO-004',
    requirements: 'Industrial style, five tiers',
    quantity: '2',
    estimatedValue: '84000.00',
    priority: 'MEDIUM',
    source: 'WEBSITE',
    stage: 'won',
    assignedTo: 'manager@demo.test',
    convert: true,
    customFields: { size_type: 'standard', material: 'metal' },
  },
  {
    fullName: 'Palwasha Khan',
    phone: '0332-6100013',
    interest: 'Corner sofa',
    productCode: 'SOF-001',
    requirements: 'Beige, easy-clean',
    quantity: '1',
    estimatedValue: '145000.00',
    priority: 'MEDIUM',
    source: 'SOCIAL',
    channel: 'FACEBOOK',
    stage: 'lost',
    lostReason: 'Price too high',
    assignedTo: 'salesperson@demo.test',
    customFields: { size_type: 'standard', material: 'fabric', color: 'Beige' },
  },
  {
    fullName: 'Rehan Aslam',
    phone: '0333-6100014',
    interest: 'Dining set',
    productCode: 'TAB-001',
    requirements: 'Marble top, six chairs',
    quantity: '1',
    estimatedValue: '190000.00',
    priority: 'MEDIUM',
    source: 'MESSAGING',
    channel: 'WHATSAPP',
    stage: 'lost',
    lostReason: 'Chose a competitor',
    assignedTo: 'salesperson@demo.test',
    customFields: { size_type: 'standard', material: 'marble' },
  },
  {
    fullName: 'Sidra Mansoor',
    phone: '0334-6100015',
    interest: 'Wardrobe and dresser',
    productCode: 'STO-002',
    requirements: 'Walnut, delivery to Lahore',
    quantity: '1',
    estimatedValue: '120000.00',
    priority: 'LOW',
    source: 'WEBSITE',
    stage: 'lost',
    lostReason: 'Delivery time too long',
    assignedTo: null,
    customFields: { size_type: 'standard', material: 'wood', wood_type: 'walnut' },
  },
];
